#!/usr/bin/python

STARTING_SKILLS = 3

COMMISSION = 8

FIELDS = ("T", "Career", "Spec", "Q", "S", "A",
          "Edu", "BT", "SR", "Rnk", "EM", "Age", "Ben")

TERM = {f: None for f in FIELDS}

DRAFT = ["Army", "Navy", "Marines"]

FALLBACK_CAREERS = ["Drifter"] + DRAFT

CAREERS = {
    'Merchants': {
        'Free Trader': {'Surv': ('Dex', 6), 'Qual': ('Int', 4), 'Adv': ('Int', 6)},
        'Merchant Marine': {'Surv': ('Edu', 5), 'Qual': ('Int', 4), 'Adv': ('Int', 7)},
        'Broker': {'Surv': ('Edu', 5), 'Qual': ('Int', 4), 'Adv': ('Int', 7)}},
    'Scholar': {
        'Physician': {'Surv': ('Edu', 4), 'Qual': ('Int', 6), 'Adv': ('Edu', 8)},
        'Scientist': {'Surv': ('Edu', 4), 'Qual': ('Int', 6), 'Adv': ('Int', 8)},
        'Field Researcher': {'Surv': ('End', 6), 'Qual': ('Int', 6), 'Adv': ('Int', 6)}},
    'Army': {
        'Cavalry': {'Surv': ('Dex', 7), 'Qual': ('End', 5), 'Adv': ('Int', 5)},
        'Support': {'Surv': ('End', 5), 'Qual': ('End', 5), 'Adv': ('Edu', 7)},
        'Infantry': {'Surv': ('Str', 6), 'Qual': ('End', 5), 'Adv': ('Edu', 6)}},
    'Navy': {
        'Line-Crew': {'Surv': ('Int', 5), 'Qual': ('Int', 6), 'Adv': ('Edu', 7)},
        'Flight': {'Surv': ('Dex', 7), 'Qual': ('Int', 6), 'Adv': ('Edu', 5)},
        'Engineering-Gunnery': {'Surv': ('Int', 6), 'Qual': ('Int', 6), 'Adv': ('Edu', 6)}},
    'Marines': {
        'Star Marine': {'Surv': ('End', 6), 'Qual': ('End', 6), 'Adv': ('Edu', 6)},
        'Support': {'Surv': ('End', 5), 'Qual': ('End', 6), 'Adv': ('Edu', 7)},
        'Ground Assault': {'Surv': ('End', 7), 'Qual': ('End', 6), 'Adv': ('Edu', 5)}},
    'Army (Officer)': {
        'Cavalry': {'Surv': ('Dex', 7), 'Qual': ('End', 5), 'Adv': ('Int', 5)},
        'Support': {'Surv': ('End', 5), 'Qual': ('End', 5), 'Adv': ('Edu', 7)},
        'Infantry': {'Surv': ('Str', 6), 'Qual': ('End', 5), 'Adv': ('Edu', 6)}},
    'Navy (Officer)': {
        'Line-Crew': {'Surv': ('Int', 5), 'Qual': ('Int', 6), 'Adv': ('Edu', 7)},
        'Flight': {'Surv': ('Dex', 7), 'Qual': ('Int', 6), 'Adv': ('Edu', 5)},
        'Engineering-Gunnery': {'Surv': ('Int', 6), 'Qual': ('Int', 6), 'Adv': ('Edu', 6)}},
    'Marines (Officer)': {
        'Star Marine': {'Surv': ('End', 6), 'Qual': ('End', 6), 'Adv': ('Edu', 6)},
        'Support': {'Surv': ('End', 5), 'Qual': ('End', 6), 'Adv': ('Edu', 7)},
        'Ground Assault': {'Surv': ('End', 7), 'Qual': ('End', 6), 'Adv': ('Edu', 5)}},
    'Scout': {
        'Exploration': {'Surv': ('End', 7), 'Qual': ('Int', 5), 'Adv': ('Edu', 7)},
        'Survey': {'Surv': ('End', 6), 'Qual': ('Int', 5), 'Adv': ('Int', 8)},
        'Courier': {'Surv': ('End', 5), 'Qual': ('Int', 5), 'Adv': ('Edu', 9)}},
    'Drifter': {
        'Scavenger': {'Surv': ('Dex', 7), 'Qual': ('Int', 0), 'Adv': ('End', 7)},
        'Wanderer': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Int', 7)},
        'Barbarian': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Str', 7)}},
    'Entertainer': {
        'Performer': {'Surv': ('Int', 5), 'Qual': ('Int', 5), 'Adv': ('Dex', 7)},
        'Journalist': {'Surv': ('Edu', 7), 'Qual': ('Int', 5), 'Adv': ('Int', 5)},
        'Artist': {'Surv': ('Soc', 6), 'Qual': ('Int', 5), 'Adv': ('Int', 6)}},
    'Rogue': {
        'Enforcer': {'Surv': ('End', 6), 'Qual': ('Dex', 6), 'Adv': ('Str', 6)},
        'Thief': {'Surv': ('Int', 6), 'Qual': ('Dex', 6), 'Adv': ('Dex', 6)},
        'Pirate': {'Surv': ('Dex', 6), 'Qual': ('Dex', 6), 'Adv': ('Int', 6)}},
    'Citizen': {
        'Worker': {'Surv': ('End', 4), 'Qual': ('Edu', 5), 'Adv': ('Edu', 8)},
        'Colonist': {'Surv': ('Int', 7), 'Qual': ('Edu', 5), 'Adv': ('End', 5)},
        'Corporate': {'Surv': ('Soc', 6), 'Qual': ('Edu', 5), 'Adv': ('Int', 6)}},
    'Nobility': {
        'Administrator': {'Surv': ('Int', 4), 'Qual': ('Soc', 10), 'Adv': ('Edu', 6)},
        'Diplomat': {'Surv': ('Int', 5), 'Qual': ('Soc', 10), 'Adv': ('Soc', 7)},
        'Dilettante': {'Surv': ('Soc', 3), 'Qual': ('Soc', 10), 'Adv': ('Int', 8)}},
    'Agent': {
        'Intelligence': {'Surv': ('Int', 7), 'Qual': ('Int', 6), 'Adv': ('Int', 5)},
        'Corporate': {'Surv': ('Int', 5), 'Qual': ('Int', 6), 'Adv': ('Int', 7)},
        'Law Enforcement': {'Surv': ('End', 6), 'Qual': ('Int', 6), 'Adv': ('Int', 6)}}
    }

AGENT = {
    'Law Enforcement': {
        'Patroller': {'Surv': ('Int', 7), 'Qual': ('Int', 5), 'Adv': ('Edu', 7)},
        'Special Operations': {'Surv': ('Int', 7), 'Qual': ('Int', 5), 'Adv': ('Int', 6)},
        'Customs': {'Surv': ('Int', 7), 'Qual': ('Int', 5), 'Adv': ('Edu', 8)}},
    'Investigator': {
        'Private Detective': {'Surv': ('Int', 6), 'Qual': ('Int', 6), 'Adv': ('Soc', 8)},
        'Inspector': {'Surv': ('Edu', 7), 'Qual': ('Int', 6), 'Adv': ('Int', 7)},
        'Undercover Agent': {'Surv': ('Int', 8), 'Qual': ('Int', 6), 'Adv': ('Edu', 6)}},
    'Spy': {
        'Field Agent': {'Surv': ('Edu', 6), 'Qual': ('Int', 7), 'Adv': ('Soc', 8)},
        'Operative': {'Surv': ('Edu', 7), 'Qual': ('Int', 7), 'Adv': ('Int', 7)},
        'Infiltrator': {'Surv': ('Edu', 8), 'Qual': ('Int', 7), 'Adv': ('Int', 6)}},
    'Analyst': {
        'Political Officer': {'Surv': ('Soc', 6), 'Qual': ('Soc', 8), 'Adv': ('Soc', 7)},
        'Technical Expert': {'Surv': ('Int', 7), 'Qual': ('Soc', 8), 'Adv': ('Int', 6)},
        'Handler': {'Surv': ('Int', 7), 'Qual': ('Soc', 8), 'Adv': ('Soc', 7)}},
    'Corporate': {
        'Security': {'Surv': ('Int', 5), 'Qual': ('Int', 6), 'Adv': ('Int', 7)},
        'Espionage': {'Surv': ('Dex', 7), 'Qual': ('Int', 6), 'Adv': ('Int', 6)},
        'Bodyguard': {'Surv': ('End', 7), 'Qual': ('Int', 6), 'Adv': ('Soc', 6)}},
    'Bounty Hunter': {
        'Ship Tracer': {'Surv': ('End', 6), 'Qual': ('Int', 7), 'Adv': ('Soc', 7)},
        'Bondsman': {'Surv': ('End', 7), 'Qual': ('Int', 7), 'Adv': ('Int', 7)},
        'Thieftaker': {'Surv': ('Dex', 7), 'Qual': ('Int', 7), 'Adv': ('Int', 6)}}
    }

CTHONIAN_STARS = {
    'Scholar': {
        'Physician': {'Surv': ('Edu', 4), 'Qual': ('Int', 6), 'Adv': ('Edu', 8)},
        'Scientist': {'Surv': ('Edu', 4), 'Qual': ('Int', 6), 'Adv': ('Int', 8)},
        'Field Researcher': {'Surv': ('End', 6), 'Qual': ('Int', 6), 'Adv': ('Int', 6)},
        'Occultist': {'Surv': ('Int', 6), 'Qual': ('Int', 6), 'Adv': ('Edu', 6)}},
    'Warden': {
        'Researcher': {'Surv': ('Int', 7), 'Qual': ('Int', 6), 'Adv': ('Int', 5)},
        'Enforcer': {'Surv': ('End', 6), 'Qual': ('Int', 6), 'Adv': ('Int', 5)},
        'Investigator': {'Surv': ('Int', 7), 'Qual': ('Int', 6), 'Adv': ('Int', 6)}},
    'Aristocrat': {
        'Administrator': {'Surv': ('Int', 4), 'Qual': ('Soc', 10), 'Adv': ('Edu', 6)},
        'Diplomat': {'Surv': ('Int', 5), 'Qual': ('Soc', 10), 'Adv': ('Soc', 7)},
        'Dilettante': {'Surv': ('Soc', 3), 'Qual': ('Soc', 10), 'Adv': ('Int', 8)}},
    }

SCOUNDREL = {
#   '': {
#       '': {'Surv': ('', ), 'Qual': ('', ), 'Adv': ('', )},
#       '': {'Surv': ('', ), 'Qual': ('', ), 'Adv': ('', )},
#       '': {'Surv': ('', ), 'Qual': ('', ), 'Adv': ('', )}},
    'Intruder': {
        'Hacker': {'Surv': ('Edu', 6), 'Qual': ('Int', 7), 'Adv': ('Int', 8)},
        'Burglar': {'Surv': ('End', 7), 'Qual': ('Int', 7), 'Adv': ('Dex', 7)},
        'Faceman': {'Surv': ('Edu', 8), 'Qual': ('Int', 7), 'Adv': ('Soc', 6)}},
    'Smuggler': {
        'Blockade Runner': {'Surv': ('Dex', 6), 'Qual': ('Edu', 6), 'Adv': ('Edu', 8)},
        'Bootlegger': {'Surv': ('End', 7), 'Qual': ('Edu', 6), 'Adv': ('Int', 7)},
        'Crew': {'Surv': ('Int', 6), 'Qual': ('Edu', 6), 'Adv': ('Edu', 8)}},
    'Organized Criminal': {
        'Assassin': {'Surv': ('End', 7), 'Qual': ('End', 8), 'Adv': ('Dex', 7)},
        'Enforcer': {'Surv': ('End', 8), 'Qual': ('End', 8), 'Adv': ('Str', 6)},
        'Co-ordinator': {'Surv': ('Edu', 6), 'Qual': ('End', 8), 'Adv': ('Int', 8)}},
    'Pirate': {
        'Corsair': {'Surv': ('Int', 7), 'Qual': ('Int', 7), 'Adv': ('Edu', 7)},
        'Boarder': {'Surv': ('End', 8), 'Qual': ('Int', 7), 'Adv': ('Int', 6)},
        'Jumpcusser': {'Surv': ('Dex', 6), 'Qual': ('Int', 7), 'Adv': ('Int', 8)}},
    'Scavenger': {
        'Wrecker': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Edu', 7)},
        'Salvage Expert': {'Surv': ('Edu', 7), 'Qual': ('Int', 0), 'Adv': ('Int', 7)},
        'Tomb Robber': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Dex', 7)}},
    'Wanderer': {
        'Hitchhiker': {'Surv': ('Soc', 7), 'Qual': ('Int', 0), 'Adv': ('Edu', 7)},
        'Vagabond': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Int', 7)},
        'Bandit': {'Surv': ('End', 7), 'Qual': ('Int', 0), 'Adv': ('Str', 7)}},
    'Barbarian': {
        'Warrior': {'Surv': ('End', 8), 'Qual': ('End', 7), 'Adv': ('Str', 6)},
        'Tribesman': {'Surv': ('End', 6), 'Qual': ('End', 7), 'Adv': ('Int', 8)},
        'Shaman': {'Surv': ('Int', 7), 'Qual': ('End', 7), 'Adv': ('Soc', 7)}},
    }


SKILLS = {
    # (Career, Spec): ((Basic Training x6), (Personal Development x6),
    #                  (Service Skills x6), (Specialist x6),
    #                  (Advanced Education x6), (Officer Skills x6))
    ("Agent", "Law Enforcement"): (("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Gun Combat", 0),
        ("Dexterity", 1), ("Endurance", 1), ("Melee", 0), ("Intelligence", 1),
        ("Athletics", 0), ("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Investigate", 0),
        ("Recon", 0), ("Streetwise", 0), ("Stealth", 0), ("Melee", 0), ("Advocate", 0),
        ("Advocate", 0), ("Comms", 0), ("Computers", 0), ("Medic", 0), ("Stealth", 0),
        ("Remote Operations", 0)),
    ("Agent", "Intelligence"): (("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Gun Combat", 0),
        ("Dexterity", 1), ("Endurance", 1), ("Melee", 0), ("Intelligence", 1),
        ("Athletics", 0), ("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Investigate", 0),
        ("Recon", 0), ("Comms", 0), ("Stealth", 0), ("Persuade", 0), ("Deception", 0),
        ("Advocate", 0), ("Comms", 0), ("Computers", 0), ("Medic", 0), ("Stealth", 0),
        ("Remote Operations", 0)),
    ("Agent", "Corporate"): (("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Gun Combat", 0),
        ("Dexterity", 1), ("Endurance", 1), ("Melee", 0), ("Intelligence", 1),
        ("Athletics", 0), ("Streetwise", 0), ("Drive", 0), ("Investigate", 0),
        ("Computers", 0), ("Recon", 0), ("Gun Combat", 0), ("Investigate", 0),
        ("Computers", 0), ("Stealth", 0), ("Gun Combat", 0), ("Deception", 0),
        ("Streetwise", 0), ("Advocate", 0), ("Comms", 0), ("Computers", 0), ("Medic", 0),
        ("Stealth", 0), ("Remote Operations", 0)),
    ("Army", "Support"): (("Drive", 0), ("Athletics", 0), ("Gun Combat", 0),
        ("Recon", 0), ("Melee", 0), ("Heavy Weapons", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0), ("Medic", 0),
        ("Melee (unarmed)", 0), ("Drive", 0), ("Athletics", 0), ("Gun Combat", 0),
        ("Recon", 0), ("Melee", 0), ("Heavy Weapons", 0), ("Mechanic", 0),
        ("Drive", 0), ("Flyer", 0), ("Explosives", 0), ("Comms", 0), ("Medic", 0),
        ("Comms", 0), ("Sensors", 0), ("Navigation", 0), ("Explosives", 0),
        ("Engineer", 0), ("Survival", 0), ("Tactics (military)", 0), ("Leadership", 0),
        ("Advocate", 0), ("Diplomat", 0), ("Tactics (military)", 0), ("Admin", 0)),
    ("Army", "Infantry"): (("Drive", 0), ("Athletics", 0), ("Gun Combat", 0),
        ("Recon", 0), ("Melee", 0), ("Heavy Weapons", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0), ("Medic", 0),
        ("Melee (unarmed)", 0), ("Drive", 0), ("Athletics", 0), ("Gun Combat", 0), ("Recon", 0),
        ("Melee", 0), ("Heavy Weapons", 0), ("Gun Combat", 0), ("Melee", 0),
        ("Heavy Weapons", 0), ("Stealth", 0), ("Athletics", 0), ("Recon", 0), ("Comms", 0),
        ("Sensors", 0), ("Navigation", 0), ("Explosives", 0), ("Engineer", 0),
        ("Survival", 0), ("Tactics (military)", 0), ("Leadership", 0), ("Advocate", 0),
        ("Diplomat", 0), ("Tactics (military)", 0), ("Admin", 0)),
    ("Army", "Cavalry"): (("Drive", 0), ("Athletics", 0), ("Gun Combat", 0),
        ("Recon", 0), ("Melee", 0), ("Heavy Weapons", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0), ("Medic", 0),
        ("Melee (unarmed)", 0), ("Drive", 0), ("Athletics", 0), ("Gun Combat", 0), ("Recon", 0),
        ("Melee", 0), ("Heavy Weapons", 0), ("Mechanic", 0), ("Drive", 0), ("Flyer", 0),
        ("Recon", 0), ("Gunner", 0), ("Sensors", 0), ("Comms", 0), ("Sensors", 0),
        ("Navigation", 0), ("Explosives", 0), ("Engineer", 0), ("Survival", 0),
        ("Tactics (military)", 0), ("Leadership", 0), ("Advocate", 0), ("Diplomat", 0),
        ("Tactics (military)", 0), ("Admin", 0)),
    ("Citizen", "Corporate"): (("Advocate", 0), ("Admin", 0), ("Broker", 0),
        ("Computers", 0), ("Diplomat", 0), ("Leadership", 0), ("Education", 1),
        ("Intelligence", 1), ("Carouse", 0), ("Gambler", 0), ("Drive", 0),
        ("Jack of all Trades", 0), ("Drive", 0), ("Flyer", 0), ("Streetwise", 0), ("Melee", 0),
        ("Steward", 0), ("Trade", 0), ("Advocate", 0), ("Admin", 0), ("Broker", 0),
        ("Computers", 0), ("Diplomat", 0), ("Leadership", 0), ("Art", 0),
        ("Advocate", 0), ("Diplomat", 0), ("Language", 0), ("Computers", 0),
        ("Medic", 0)),
    ("Citizen", "Worker"): (("Drive", 0), ("Mechanic", 0), ("Trade", 0),
        ("Engineer", 0), ("Trade", 0), ("Science", 0), ("Education", 1),
        ("Intelligence", 1), ("Carouse", 0), ("Gambler", 0), ("Drive", 0),
        ("Jack of all Trades", 0), ("Drive", 0), ("Flyer", 0), ("Streetwise", 0), ("Melee", 0),
        ("Steward", 0), ("Trade", 0), ("Drive", 0), ("Mechanic", 0), ("Trade", 0),
        ("Engineer", 0), ("Trade", 0), ("Any Science", 0), ("Art", 0),
        ("Advocate", 0), ("Diplomat", 0), ("Language", 0), ("Computers", 0),
        ("Medic", 0)),
    ("Citizen", "Colonist"): (("Animals", 0), ("Athletics", 0),
        ("Jack of all Trades", 0), ("Drive", 0), ("Survival", 0), ("Recon", 0), ("Education", 1),
        ("Intelligence", 1), ("Carouse", 0), ("Gambler", 0), ("Drive", 0),
        ("Jack of all Trades", 0), ("Drive", 0), ("Flyer", 0), ("Streetwise", 0), ("Melee", 0),
        ("Steward", 0), ("Trade", 0), ("Animals", 0), ("Athletics", 0),
        ("Jack of all Trades", 0), ("Drive", 0), ("Survival", 0), ("Recon", 0), ("Art", 0),
        ("Advocate", 0), ("Diplomat", 0), ("Language", 0), ("Computers", 0), ("Medic", 0)),
    ("Drifter", "Barbarian"): (("Animals", 0), ("Carouse", 0), ("Melee", 0),
        ("Stealth", 0), ("Seafarer", 0), ("Survival", 0), ("Strength", 1),
        ("Endurance", 1), ("Dexterity", 1), ("Jack of all Trades", 0),
        ("Endurance", 1), ("Intelligence", 1), ("Athletics", 0),
        ("Melee (unarmed)", 0), ("Recon", 0), ("Streetwise", 0), ("Stealth", 0),
        ("Survival", 0), ("Animals", 0), ("Carouse", 0), ("Melee (blade)", 0),
        ("Stealth", 0), ("Seafarer", 0), ("Survival", 0)),
    ("Drifter", "Wanderer"): (("Athletics", 0), ("Deception", 0), ("Recon", 0),
        ("Stealth", 0), ("Streetwise", 0), ("Survival", 0), ("Strength", 1),
        ("Endurance", 1), ("Dexterity", 1), ("Jack of all Trades", 0),
        ("Endurance", 1), ("Intelligence", 1), ("Athletics", 0),
        ("Melee (unarmed)", 0), ("Recon", 0), ("Streetwise", 0), ("Stealth", 0),
        ("Survival", 0), ("Athletics", 0), ("Deception", 0), ("Recon", 0),
        ("Stealth", 0), ("Streetwise", 0), ("Survival", 0)),
    ("Drifter", "Scavenger"): (("Pilot", 0), ("Mechanic", 0), ("Astrogation", 0),
        ("Vacc Suit", 0), ("Zero-G", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Endurance", 1), ("Dexterity", 1), ("Jack of all Trades", 0),
        ("Endurance", 1), ("Intelligence", 1), ("Athletics", 0),
        ("Melee (unarmed)", 0), ("Recon", 0), ("Streetwise", 0), ("Stealth", 0),
        ("Survival", 0), ("Pilot (small craft)", 0), ("Mechanic", 0),
        ("Astrogation", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Gun Combat", 0)),
    ("Entertainer", "Artist"): (("Art", 0), ("Art", 0), ("Carouse", 0),
        ("Deception", 0), ("Persuade", 0), ("Steward", 0), ("Dexterity", 1),
        ("Intelligence", 1), ("Social", 1), ("Education", 1), ("Carouse", 0),
        ("Stealth", 0), ("Art", 0), ("Art", 0), ("Carouse", 0), ("Deception", 0),
        ("Persuade", 0), ("Steward", 0), ("Art", 0), ("Carouse", 0),
        ("Computers", 0), ("Gambler", 0), ("Persuade", 0), ("Trade", 0),
        ("Advocate", 0), ("Art", 0), ("Deception", 0), ("Any Science", 0),
        ("Streetwise", 0), ("Diplomat", 0)),
    ("Entertainer", "Journalist"): (("Art", 0), ("Art", 0), ("Carouse", 0),
        ("Deception", 0), ("Persuade", 0), ("Steward", 0), ("Dexterity", 1),
        ("Intelligence", 1), ("Social", 1), ("Education", 1), ("Carouse", 0),
        ("Stealth", 0), ("Art", 0), ("Art", 0), ("Carouse", 0), ("Deception", 0),
        ("Persuade", 0), ("Steward", 0), ("Art (writing or holography)", 0),
        ("Comms", 0), ("Computers", 0), ("Investigate", 0), ("Recon", 0),
        ("Streetwise", 0), ("Advocate", 0), ("Art", 0), ("Deception", 0),
        ("Any Science", 0), ("Streetwise", 0), ("Diplomat", 0)),
    ("Entertainer", "Performer"): (("Art", 0), ("Art", 0), ("Carouse", 0),
        ("Deception", 0), ("Persuade", 0), ("Steward", 0), ("Dexterity", 1),
        ("Intelligence", 1), ("Social", 1), ("Education", 1), ("Carouse", 0),
        ("Stealth", 0), ("Art", 0), ("Art", 0), ("Carouse", 0), ("Deception", 0),
        ("Persuade", 0), ("Steward", 0), "Art (acting/dance/instrument)",
        ("Athletics (coordination or endurance)", 0), ("Carouse", 0),
        ("Deception", 0), ("Stealth", 0), ("Streetwise", 0), ("Advocate", 0),
        ("Art", 0), ("Deception", 0), ("Any Science", 0), ("Streetwise", 0),
        ("Diplomat", 0)),
    ("Marines", "Support"): (("Athletics", 0), ("Battle Dress", 0), ("Tactics", 0),
        ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0), ("Melee (unarmed)", 0),
        ("Melee (armed)", 0), ("Athletics", 0), ("Battle Dress", 0), ("Tactics", 0),
        ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0), ("Comms", 0),
        ("Mechanic", 0), ("Drive or Flyer", 0), ("Medic", 0), ("Heavy Weapons", 0),
        ("Gun Combat", 0), ("Medic", 0), ("Survival", 0), ("Explosives", 0),
        ("Engineer", 0), ("Pilot", 0), ("Medic", 0), ("Leadership", 0),
        ("Tactics", 0), ("Admin", 0), ("Advocate", 0), ("Battle Dress", 0),
        ("Leadership", 0)),
    ("Marines", "Star Marines"): (("Athletics", 0), ("Battle Dress", 0),
        ("Tactics", 0), ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0),
        ("Strength", 1), ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0),
        ("Melee (unarmed)", 0), ("Melee (armed)", 0), ("Athletics", 0), ("Battle Dress", 0),
        ("Tactics", 0), ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0),
        ("Battle Dress", 0), ("Zero-G", 0), ("Gunner", 0), ("Melee (blade)", 0),
        ("Sensors", 0), ("Gun Combat", 0), ("Medic", 0), ("Survival", 0),
        ("Explosives", 0), ("Engineer", 0), ("Pilot", 0), ("Medic", 0),
        ("Leadership", 0), ("Tactics", 0), ("Admin", 0), ("Advocate", 0),
        ("Battle Dress", 0), ("Leadership", 0)),
    ("Marines", "Ground Assault"): (("Athletics", 0), ("Battle Dress", 0),
        ("Tactics", 0), ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0),
        ("Strength", 1), ("Dexterity", 1), ("Endurance", 1), ("Gambler", 0),
        ("Melee (unarmed)", 0), ("Melee (armed)", 0), ("Athletics", 0), ("Battle Dress", 0),
        ("Tactics", 0), ("Heavy Weapons", 0), ("Gun Combat", 0), ("Stealth", 0),
        ("Battle Dress", 0), ("Heavy Weapons", 0), ("Recon", 0),
        ("Melee (blade)", 0), ("Tactics (military)", 0), ("Gun Combat", 0), ("Medic", 0),
        ("Survival", 0), ("Explosives", 0), ("Engineer", 0), ("Pilot", 0),
        ("Medic", 0), ("Leadership", 0), ("Tactics", 0), ("Admin", 0),
        ("Advocate", 0), ("Battle Dress", 0), ("Leadership", 0)),
    ("Merchant", "Merchant Marine"): (("Drive", 0), ("Vacc Suit", 0), ("Broker", 0),
        ("Steward", 0), ("Comms", 0), ("Persuade", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1),
        ("Melee (blade)", 0), ("Streetwise", 0), ("Drive", 0), ("Vacc Suit", 0),
        ("Broker", 0), ("Steward", 0), ("Comms", 0), ("Persuade", 0),
        ("Pilot (spacecraft or capital ships)", 0), ("Vacc Suit", 0), ("Zero-G", 0),
        ("Mechanic", 0), ("Engineer", 0), ("Gunner", 0), ("Social Sciences", 0),
        ("Astrogation", 0), ("Computers", 0), ("Pilot", 0), ("Admin", 0),
        ("Advocate", 0)),
    ("Merchant", "Free Trader"): (("Drive", 0), ("Vacc Suit", 0), ("Broker", 0),
        ("Steward", 0), ("Comms", 0), ("Persuade", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1),
        ("Melee (blade)", 0), ("Streetwise", 0), ("Drive", 0), ("Vacc Suit", 0),
        ("Broker", 0), ("Steward", 0), ("Comms", 0), ("Persuade", 0),
        ("Pilot (spacecraft)", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Mechanic", 0),
        ("Engineer", 0), ("Sensors", 0), ("Social Sciences", 0), ("Astrogation", 0),
        ("Computers", 0), ("Pilot", 0), ("Admin", 0), ("Advocate", 0)),
    ("Merchant", "Broker"): (("Drive", 0), ("Vacc Suit", 0), ("Broker", 0),
        ("Steward", 0), ("Comms", 0), ("Persuade", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1),
        ("Melee (blade)", 0), ("Streetwise", 0), ("Drive", 0), ("Vacc Suit", 0),
        ("Broker", 0), ("Steward", 0), ("Comms", 0), ("Persuade", 0), ("Admin", 0),
        ("Advocate", 0), ("Broker", 0), ("Streetwise", 0), ("Deception", 0),
        ("Persuade", 0), ("Social Sciences", 0), ("Astrogation", 0),
        ("Computers", 0), ("Pilot", 0), ("Admin", 0), ("Advocate", 0)),
    ("Navy", "Line/Crew"): (("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0),
        ("Gunner", 0), ("Mechanic", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1), ("Education", 1),
        ("Social", 1), ("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Gunner", 0),
        ("Mechanic", 0), ("Gun Combat", 0), ("Comms", 0), ("Mechanic", 0),
        ("Gun Combat", 0), ("Sensors", 0), ("Melee", 0), ("Vacc Suit", 0),
        ("Remote Operations", 0), ("Astrogation", 0), ("Engineer", 0), ("Computers", 0),
        ("Navigation", 0), ("Admin", 0), ("Leadership", 0), ("Tactics (naval)", 0),
        ("Pilot", 0), ("Melee (blade)", 0), ("Admin", 0), ("Tactics (naval)", 0)),
    ("Navy", "Engineering/ Gunnery"): (("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0),
        ("Gunner", 0), ("Mechanic", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1), ("Education", 1),
        ("Social", 1), ("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Gunner", 0),
        ("Mechanic", 0), ("Gun Combat", 0), ("Engineer", 0), ("Mechanic", 0),
        ("Sensors", 0), ("Engineer", 0), ("Gunner", 0), ("Computers", 0),
        ("Remote Operations", 0), ("Astrogation", 0), ("Engineer", 0), ("Computers", 0),
        ("Navigation", 0), ("Admin", 0), ("Leadership", 0), ("Tactics (naval)", 0),
        ("Pilot", 0), ("Melee (blade)", 0), ("Admin", 0), ("Tactics (naval)", 0)),
    ("Navy", "Flight"): (("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Gunner", 0),
        ("Mechanic", 0), ("Gun Combat", 0), ("Strength", 1), ("Dexterity", 1),
        ("Endurance", 1), ("Intelligence", 1), ("Education", 1), ("Social", 1),
        ("Pilot", 0), ("Vacc Suit", 0), ("Zero-G", 0), ("Gunner", 0),
        ("Mechanic", 0), ("Gun Combat", 0), ("Pilot", 0), ("Flyer", 0),
        ("Gunner", 0), ("Pilot (small craft)", 0), ("Astrogation", 0),
        ("Zero-G", 0), ("Remote Operations", 0), ("Astrogation", 0),
        ("Engineer", 0), ("Computers", 0), ("Navigation", 0), ("Admin", 0),
        ("Leadership", 0), ("Tactics (naval)", 0), ("Pilot", 0),
        ("Melee (blade)", 0), ("Admin", 0), ("Tactics (naval)", 0)),
    ("Nobility", "Administrator"): (("Admin", 0), ("Advocate", 0), ("Comms", 0),
        ("Diplomat", 0), ("Investigate", 0), ("Persuade", 0), ("Carouse", 0),
        ("Education", 1), ("Deception", 0), ("Dexterity", 1), ("Melee (blade)", 0),
        ("Social", 1), ("Admin", 0), ("Advocate", 0), ("Comms", 0), ("Diplomat", 0),
        ("Investigate", 0), ("Persuade", 0), ("Admin", 0), ("Advocate", 0),
        ("Broker", 0), ("Diplomat", 0), ("Leadership", 0), ("Persuade", 0),
        ("Admin", 0), ("Advocate", 0), ("Language", 0), ("Leadership", 0),
        ("Diplomat", 0), ("Computers", 0)),
    ("Nobility", "Diplomat"): (("Admin", 0), ("Advocate", 0), ("Comms", 0),
        ("Diplomat", 0), ("Investigate", 0), ("Persuade", 0), ("Carouse", 0),
        ("Education", 1), ("Deception", 0), ("Dexterity", 1), ("Melee (blade)", 0),
        ("Social", 1), ("Admin", 0), ("Advocate", 0), ("Comms", 0), ("Diplomat", 0),
        ("Investigate", 0), ("Persuade", 0), ("Advocate", 0), ("Carouse", 0),
        ("Comms", 0), ("Steward", 0), ("Diplomat", 0), ("Deception", 0),
        ("Admin", 0), ("Advocate", 0), ("Language", 0), ("Leadership", 0),
        ("Diplomat", 0), ("Computers", 0)),
    ("Nobility", "Dilettante"): (("Admin", 0), ("Advocate", 0), ("Comms", 0),
        ("Diplomat", 0), ("Investigate", 0), ("Persuade", 0), ("Carouse", 0),
        ("Education", 1), ("Deception", 0), ("Dexterity", 1), ("Melee (blade)", 0),
        ("Social", 1), ("Admin", 0), ("Advocate", 0), ("Comms", 0), ("Diplomat", 0),
        ("Investigate", 0), ("Persuade", 0), ("Carouse", 0), ("Deception", 0),
        ("Flyer", 0), ("Streetwise", 0), ("Gambler", 0), ("Jack of all Trades", 0),
        ("Admin", 0), ("Advocate", 0), ("Language", 0), ("Leadership", 0),
        ("Diplomat", 0), ("Computers", 0)),
    ("Rogue", "Thief"): (("Deception", 0), ("Recon", 0), ("Athletics", 0),
        ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0), ("Carouse", 0), ("Dexterity", 1),
        ("Endurance", 1), ("Gambler", 0), ("Melee", 0), ("Gun Combat", 0), ("Deception", 0),
        ("Recon", 0), ("Athletics", 0), ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0),
        ("Stealth", 0), ("Computers", 0), ("Remote Operations", 0), ("Streetwise", 0),
        ("Deception", 0), ("Athletics (co-ordination)", 0), ("Computers", 0), ("Comms", 0),
        ("Medic", 0), ("Investigate", 0), ("Persuade", 0), ("Advocate", 0)),
    ("Rogue", "Enforcer"): (("Deception", 0), ("Recon", 0), ("Athletics", 0),
        ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0), ("Carouse", 0), ("Dexterity", 1),
        ("Endurance", 1), ("Gambler", 0), ("Melee", 0), ("Gun Combat", 0), ("Deception", 0),
        ("Recon", 0), ("Athletics", 0), ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0),
        ("Gun Combat", 0), ("Melee", 0), ("Streetwise", 0), ("Persuade", 0),
        ("Athletics", 0), ("Drive", 0), ("Computers", 0), ("Comms", 0), ("Medic", 0),
        ("Investigate", 0), ("Persuade", 0), ("Advocate", 0)),
    ("Rogue", "Pirate"): (("Deception", 0), ("Recon", 0), ("Athletics", 0),
        ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0), ("Carouse", 0), ("Dexterity", 1),
        ("Endurance", 1), ("Gambler", 0), ("Melee", 0), ("Gun Combat", 0), ("Deception", 0),
        ("Recon", 0), ("Athletics", 0), ("Gun Combat", 0), ("Stealth", 0), ("Streetwise", 0),
        ("Pilot", 0), ("Astrogation", 0), ("Gunner", 0), ("Engineer", 0), ("Vacc Suit", 0),
        ("Melee (blade)", 0), ("Computers", 0), ("Comms", 0), ("Medic", 0),
        ("Investigate", 0), ("Persuade", 0), ("Advocate", 0)),
    ("Scholar", "Field Researcher"): (("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Science", 0), ("Intelligence", 1),
        ("Education", 1), ("Social", 1), ("Dexterity", 1), ("Endurance", 1),
        ("Computers", 0), ("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Any Science", 0), ("Sensors", 0),
        ("Diplomat", 0), ("Language", 0), ("Survival", 0), ("Investigate", 0),
        ("Any Science", 0), ("Art", 0), ("Advocate", 0), ("Computers", 0), ("Language", 0),
        ("Engineer", 0), ("Any Science", 0)),
    ("Scholar", "Scientist"): (("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Science", 0), ("Intelligence", 1),
        ("Education", 1), ("Social", 1), ("Dexterity", 1), ("Endurance", 1),
        ("Computers", 0), ("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Any Science", 0), ("Admin", 0),
        ("Engineer", 0), ("Any Science", 0), ("Sensors", 0), ("Computers", 0),
        ("Any Science", 0), ("Art", 0), ("Advocate", 0), ("Computers", 0), ("Language", 0),
        ("Engineer", 0), ("Any Science", 0)),
    ("Scholar", "Physician"): (("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Science", 0), ("Intelligence", 1),
        ("Education", 1), ("Social", 1), ("Dexterity", 1), ("Endurance", 1),
        ("Computers", 0), ("Comms", 0), ("Computers", 0), ("Diplomat", 0),
        ("Medic", 0), ("Investigate", 0), ("Any Science", 0), ("Medic", 0),
        ("Comms", 0), ("Investigate", 0), ("Medic", 0), ("Persuade", 0),
        ("Any Science", 0), ("Art", 0), ("Advocate", 0), ("Computers", 0), ("Language", 0),
        ("Engineer", 0), ("Any Science", 0)),
    ("Scout", "Courier"): (("Pilot", 0), ("Survival", 0), ("Mechanic", 0),
        ("Astrogation", 0), ("Comms", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1), ("Education", 1),
        ("Jack of all Trades", 0), ("Pilot (spacecraft or small craft)", 0),
        ("Survival", 0), ("Mechanic", 0), ("Astrogation", 0), ("Comms", 0),
        ("Gun Combat", 0), ("Comms", 0), ("Sensors", 0), ("Pilot (spacecraft)", 0),
        ("Vacc Suit", 0), ("Zero-G", 0), ("Astrogation", 0), ("Medic", 0),
        ("Navigation", 0), ("Engineer", 0), ("Computer", 0), ("Space Sciences", 0),
        ("Jack of all Trades", 0)),
    ("Scout", "Survey"): (("Pilot", 0), ("Survival", 0), ("Mechanic", 0),
        ("Astrogation", 0), ("Comms", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1), ("Education", 1),
        ("Jack of all Trades", 0), ("Pilot (spacecraft or small craft)", 0),
        ("Survival", 0), ("Mechanic", 0), ("Astrogation", 0), ("Comms", 0),
        ("Gun Combat", 0), ("Sensors", 0), ("Persuade", 0), ("Pilot (small craft)", 0),
        ("Navigation", 0), ("Diplomat", 0), ("Streetwise", 0), ("Medic", 0),
        ("Navigation", 0), ("Engineer", 0), ("Computer", 0), ("Space Sciences", 0),
        ("Jack of all Trades", 0)),
    ("Scout", "Exploration"): (("Pilot", 0), ("Survival", 0), ("Mechanic", 0),
        ("Astrogation", 0), ("Comms", 0), ("Gun Combat", 0), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Intelligence", 1), ("Education", 1),
        ("Jack of all Trades", 0), ("Pilot (spacecraft or small craft)", 0),
        ("Survival", 0), ("Mechanic", 0), ("Astrogation", 0), ("Comms", 0),
        ("Gun Combat", 0), ("Comms", 0), ("Pilot (spacecraft)", 0),
        ("Pilot (small craft)", 0), ("Life Sciences", 0), ("Stealth", 0), ("Recon", 0),
        ("Medic", 0), ("Navigation", 0), ("Engineer", 0), ("Computer", 0),
        ("Space Sciences", 0), ("Jack of all Trades", 0)),
    ("Psion", "Wild Talent"): (("Telepathy", 0), ("Clairvoyance", 0),
        ("Telekinesis", 0), ("Awareness", 0), ("Teleportation", 0),
        ("Any Skill", 0), ("Education", 1), ("Intelligence", 1), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Psionic", 1), ("Telepathy", 0),
        ("Clairvoyance", 0), ("Telekinesis", 0), ("Awareness", 0),
        ("Teleportation", 0), ("Any Skill", 0), ("Telepathy", 0),
        ("Telekinesis", 0), ("Deception", 0), ("Stealth", 0), ("Streetwise", 0),
        ("Melee or Gun Combat", 0), ("Comms", 0), ("Computers", 0), ("Language", 0),
        ("Medic", 0), ("Life Sciences", 0), ("Space Sciences", 0)),
    ("Psion", "Adept"): (("Telepathy", 0), ("Clairvoyance", 0), ("Telekinesis", 0),
        ("Awareness", 0), ("Teleportation", 0), ("Any Skill", 0), ("Education", 1),
        ("Intelligence", 1), ("Strength", 1), ("Dexterity", 1), ("Endurance", 1),
        ("Psionic", 1), ("Telepathy", 0), ("Clairvoyance", 0), ("Telekinesis", 0),
        ("Awareness", 0), ("Teleportation", 0), ("Any Skill", 0), ("Telepathy", 0),
        ("Clairvoyance", 0), ("Awareness", 0), ("Medic", 0), ("Persuade", 0),
        ("Social Sciences", 0), ("Comms", 0), ("Computers", 0), ("Language", 0),
        ("Medic", 0), ("Life Sciences", 0), ("Space Sciences", 0)),
    ("Psion", "Psi-Warrior"): (("Telepathy", 0), ("Clairvoyance", 0),
        ("Telekinesis", 0), ("Awareness", 0), ("Teleportation", 0),
        ("Any Skill", 0), ("Education", 1), ("Intelligence", 1), ("Strength", 1),
        ("Dexterity", 1), ("Endurance", 1), ("Psionic", 1), ("Telepathy", 0),
        ("Clairvoyance", 0), ("Telekinesis", 0), ("Awareness", 0),
        ("Teleportation", 0), ("Any Skill", 0), ("Telepathy", 0), ("Awareness", 0),
        ("Teleportation", 0), ("Gun Combat", 0), ("Battle Dress", 0), ("Recon", 0),
        ("Comms", 0), ("Computers", 0), ("Language", 0), ("Medic", 0),
        ("Life Sciences", 0), ("Space Sciences", 0)),
}
